name: deploying_stuff
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    branches:
      - main
      - new_branch
  paths-ignore:
    - '.github/workflows/*'


jobs:
  push_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Download GitHub Code
        uses: actions/checkout@v3
      - name: Download Docker nginx
        run: |
          docker image pull nginx
          docker image ls
          docker container run -d -p 8080:80 nginx
      - name: Test Web Deployment
        run: |
          python3 -c "import requests; r=requests.get('http://localhost:8080'); print(r.status_code)"
          curl -s localhost:8080

  dummy_job:
    needs: [push_workflow]
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Object Inspection
        run: echo "${{    toJSON(   github   )     }}"