name: deploying_stuff
on: push

jobs:
  push_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: check download
        run: |
          docker image pull nginx
          docker image ls
          docker container run -d -p 8080:80 nginx
      - name: Test Web Deployment
        run: |
          python3 -c "import requests; r=requests.get('http://localhost:8080'); print(r.status_code)"
          curl -s localhost:8080