name: deploying_stuff
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'


jobs:
  docker_test:
    runs-on: ubuntu-latest
    steps:
      - name: Download GitHub Code
        uses: actions/checkout@v3
      - name: Download Docker nginx
        run: |
          docker image pull nginx
          docker image ls
          docker container run -d -p 8080:80 nginx
      - name: Test Web Deployment
        run: |
          python3 -c "import requests; r=requests.get('http://localhost:8080'); print(r.status_code)"
          curl -s localhost:8080

  dummy_job:
    needs: [docker_test]
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Object Inspection
        run: echo "${{toJSON(github)}}"

  get_file_from_vm:
    needs: [docker_test]
    runs-on: ubuntu-latest

    steps:
      - name: Make a temp file
        run: |
          touch new_file
          echo "some text in the new file" > new_file
          echo "FILE_PATH=$(pwd)/new_file" >> $GITHUB_ENV
      - name: Upload the artifact for viewing
        uses: actions/upload-artifact@v3
        with:
          name: uploaded_file_ready_to_view
          path: "${{  env.FILE_PATH  }}"