name: deploying_stuff
on: push

jobs:
  push_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: download code
       uses: actions/checkout@v3
      - name: inspect download
        run: |
          pwd
          ls -lart